### ISSUE TITLE
Android App is using data even if qabel is not used active

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#623] opened 2016-08-21 15:00 UTC
I recognized that qabel used a loz of traffic even if i don't use it actively at the moment...
Can this be debugged or is this intended?
![tmp_25368-screenshot_20160821-165504-1333929381](https://cloud.githubusercontent.com/assets/3028703/17837971/2c9d5a8e-67c1-11e6-8dd1-c35d6b72337a.png)

**Comment by audax** [comment] 2016-08-22 08:37
It is fixed in /master. The data usage comes from a bug in the drop message fetching where it always fetched all messages for an identity and not just the new messages.

The problem is much worse in the release version than in the current master because it polls every 3 minutes while the current version only polls every 3 hours and uses FCM for push messaging.

**Closed by audax** 2016-08-22 08:37 UTC
Labels: bug
